spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/elaastix
    username: elaastix
    password: elaastix

# Disable OpenTelemetry in development
management:
  otlp.metrics.export.enabled: false
  logging.export.otlp.enabled: false
  tracing.export.otlp.enabled: false
